version: '3.9'

services:
  db:
    image: mysql:5.7
    volumes:
      - misdatos:/var/lib/mysql
      - miconfig:/etc/configjesus
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: alumno1234
      MYSQL_DATABASE: dbwp
      MYSQL_USER: userwp
      MYSQL_PASSWORD: alumno1234

  wp:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
      - '8080:443'
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: userwp
      WORDPRESS_DB_PASSWORD: alumno1234
      WORDPRESS_DB_NAME: dbwp
    volumes:
      - ./wordpress:/var/www/html
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    ports:
      - "8888:80"
    restart: always
    environment:
      PMA_ARBITRARY: 1
    

volumes:
  misdatos:
  miconfig:
